pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'

variables:
  ACRName: 'insightdemocontainerregistry.azurecr.io'
  ImageName: 'insightappservice'

trigger:
  - master

stages:
  - stage: Build
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job:
        displayName: Building the App
        steps:
          - task: Docker@0
            displayName: 'Build an image'
            inputs:
              azureSubscription: AzureSubscription
              azureContainerRegistry: '$(ACRName)'
              dockerFile: src/dockerfile
              imageName: '$(ImageName):$(Build.BuildId)'

          - task: Docker@0
            displayName: 'Push an image'
            inputs:
              azureSubscription: AzureSubscription
              azureContainerRegistry: '$(ACRName)'
              action: 'Push an image'
              imageName: '$(ImageName):$(Build.BuildId)'

          - task: AzureAppServiceManage@0
            displayName: 'Swap Slots: Demo-App-DemoApp'
            inputs:
              azureSubscription: 
              WebAppName: 'Demo-App-DemoApp'
              ResourceGroupName: 'Demo-ARG-AppServiceDemo'
              SourceSlot: staging
            enabled: false

  - stage: Staging
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job:
        displayName: Push to Staging Slot
        steps:
        - task: AzureRmWebAppDeployment@4
          displayName: 'Deploy Image to Staging'
          inputs:
            azureSubscription: AzureSubscription
            appType: webAppContainer
            WebAppName: 'Demo-App-DemoApp'
            deployToSlotOrASE: true
            ResourceGroupName: 'Demo-ARG-AppServiceDemo'
            SlotName: staging
            DockerNamespace: '$(ACRName)'
            DockerRepository: '$(ImageName)'
            DockerImageTag: '$(Build.BuildId)'

  - stage: Production
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job:
        displayName: Swap Slots
        steps:
        - task: AzureAppServiceManage@0
          displayName: 'Swap Slots: Demo-App-DemoApp'
          inputs:
            azureSubscription: 
            WebAppName: 'Demo-App-DemoApp'
            ResourceGroupName: 'Demo-ARG-AppServiceDemo'
            SourceSlot: staging
          enabled: false
